[build-system]
requires = ["setuptools", "wheel",
'nose','pillow','scipy','pandas','numpy','matplotlib','h5py',
       'histutils','dmcutils','morecvutils','pyoptflow',
       'fitsio','astropy','tifffile',
 "nose"] 
